// Generated by Wrangler on Thu Jun 06 2024 01:17:25 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	APP_NAME: "GameNews";
	WP_SITE: "gamenews.programacionavanzadaweb.com";
	API_HOST: string;
}
