// Generated by Wrangler on Wed Jun 12 2024 12:53:25 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	APP_NAME: "GameNews";
	GAMENEWS_API: "http://localhost:3000";
	WP_SITE: "gamenews.programacionavanzadaweb.com";
	GAMENEWS_TOKEN: string;
}
