// Generated by Wrangler on Wed Jun 12 2024 20:01:24 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	NODE_ENV: "local";
	APP_NAME: "GameNewsLOCAL";
	GAMENEWS_API: "http://localhost:3000";
	WP_SITE: "https://gamenews.programacionavanzadaweb.com";
	GAMENEWS_TOKEN: string;
}
