[vars]
APP_NAME = "GameNews"
GAMENEWS_API = "http://localhost:3000"
WP_SITE = "gamenews.programacionavanzadaweb.com"

[env.develop.vars]
WP_SITE = "gamenews.programacionavanzadaweb.com"

[env.production.vars]
WP_SITE = "gamenews.programacionavanzadaweb.com"
