[vars]
NODE_ENV = "local"
APP_NAME = "GameNewsLOCAL"
GAMENEWS_API = "http://localhost:3000"
WP_SITE = "https://gamenews.programacionavanzadaweb.com"

[env.develop.vars]
NODE_ENV = "development"
APP_NAME = "GameNewsDEV"
WP_SITE = "https://gamenews.programacionavanzadaweb.com"

[env.production.vars]
NODE_ENV = "production"
APP_NAME = "GameNews"
WP_SITE = "https://gamenews.programacionavanzadaweb.com"
